-- ================================================================================
--   postgres SQL DDL Script File
-- ================================================================================


-- ===============================================================================
-- 
--   Generated by:      tedia2sql -- v1.2.12
--                      See http://tedia2sql.tigris.org/AUTHORS.html for tedia2sql author information
-- 
--   Target Database:   postgres
--   Generated at:      Sun Jul 29 11:07:16 2007
--   Input Files:       Diagrama_Base_De_Datos_GNUPanel.dia
-- 
-- ================================================================================



-- Generated SQL Constraints Drop statements
-- --------------------------------------------------------------------
--     Target Database:   postgres
--     SQL Generator:     tedia2sql -- v1.2.12
--     Generated at:      Sun Jul 29 11:07:14 2007
--     Input Files:       Diagrama_Base_De_Datos_GNUPanel.dia

-- alter table gnupanel_usuario_data drop constraint gnupanel_u_d-- (is implicitly done)
-- alter table gnupanel_usuario drop constraint gnupanel_r_u-- (is implicitly done)
-- alter table gnupanel_reseller drop constraint gnupanel_a_r-- (is implicitly done)
-- alter table gnupanel_reseller_data drop constraint gnupanel_r_r_d-- (is implicitly done)
-- alter table gnupanel_usuarios_planes drop constraint gnupanel_r_u_p-- (is implicitly done)
-- alter table gnupanel_usuario_plan drop constraint gnupanel_u_u_p-- (is implicitly done)
-- alter table gnupanel_usuario_estado drop constraint gnupanel_u_u_e-- (is implicitly done)
-- alter table gnupanel_tickets_usuarios drop constraint gnupanel_u_t_p-- (is implicitly done)
-- alter table gnupanel_pdns_domains drop constraint gnupanel_u_p_d-- (is implicitly done)
-- alter table gnupanel_postfix_mailuser drop constraint gnupanel_p_t_p_m-- (is implicitly done)
-- alter table gnupanel_postfix_virtual drop constraint gnupanel_p_m_p_v-- (is implicitly done)
-- alter table gnupanel_pdns_records drop constraint gnupanel_p_d_r-- (is implicitly done)
-- alter table gnupanel_proftpd_ftpgroup drop constraint gnupanel_p_f_p_f-- (is implicitly done)
-- alter table gnupanel_proftpd_ftpquotalimits drop constraint gnupanel_p_f_p_fquli-- (is implicitly done)
-- alter table gnupanel_proftpd_ftpquotatallies drop constraint gnupanel_p_fquli_p_fquta-- (is implicitly done)
-- alter table gnupanel_postfix_alias drop constraint gnupanel_p_t_p_a-- (is implicitly done)
-- alter table gnupanel_apacheconf drop constraint pdns_p_d_a-- (is implicitly done)
-- alter table gnupanel_apache_user drop constraint gnupanel_a_a_u-- (is implicitly done)
-- alter table gnupanel_postfix_transport drop constraint gnupanel_p_d_p_t-- (is implicitly done)
-- alter table gnupanel_proftpd_ftpuser drop constraint gnupanel_p_d_p_u-- (is implicitly done)
-- alter table gnupanel_transferencias drop constraint gnupanel_p_d_t-- (is implicitly done)
-- alter table gnupanel_espacio drop constraint gnupanel_t_e-- (is implicitly done)
-- alter table gnupanel_reseller_plan drop constraint gnupanel_r_r_p-- (is implicitly done)
-- alter table gnupanel_reseller_estado drop constraint gnupanel_r_r_e-- (is implicitly done)
-- alter table gnupanel_reseller_planes drop constraint gnupanel_a_r_p-- (is implicitly done)
-- alter table gnupanel_tickets_reseller drop constraint gnupanel_r_t_r-- (is implicitly done)
-- alter table gnupanel_reseller drop constraint gnupanel_i_s_u-- (is implicitly done)
-- alter table gnupanel_bases_de_datos drop constraint gnupanel_u_b_p-- (is implicitly done)
-- alter table gnupanel_usuarios_base drop constraint gnupanel_b_p_u_p-- (is implicitly done)
-- alter table gnupanel_usuarios_facturas drop constraint gnupanel_r_u_f-- (is implicitly done)
-- alter table gnupanel_reseller_facturas drop constraint gnupanel_a_r_f-- (is implicitly done)
-- alter table gnupanel_admin_lang drop constraint gnupanel_a_a_l-- (is implicitly done)
-- alter table gnupanel_reseller_lang drop constraint gnupanel_r_r_l-- (is implicitly done)
-- alter table gnupanel_usuario_lang drop constraint gnupanel_u_u_l-- (is implicitly done)
-- alter table gnupanel_admin_sets drop constraint gnupanel_a_a_s-- (is implicitly done)
-- alter table gnupanel_reseller_sets drop constraint gnupanel_r_r_s-- (is implicitly done)
-- alter table gnupanel_usuario_sets drop constraint gnupanel_u_u_s-- (is implicitly done)
-- alter table gnupanel_server_data drop constraint gnupanel_s_s_d-- (is implicitly done)
-- alter table gnupanel_ips_servidor drop constraint gnupanel_s_i_s-- (is implicitly done)
-- alter table gnupanel_reseller_extras drop constraint gnupanel_r_r_e-- (is implicitly done)
-- alter table gnupanel_usuario_extras drop constraint gnupanel_u_u_e-- (is implicitly done)
-- alter table gnupanel_servidores_secundarios drop constraint gnupanel_s_s_s-- (is implicitly done)
-- alter table gnupanel_divisas_reseller drop constraint gnupanel_r_d_r-- (is implicitly done)
-- alter table gnupanel_divisas_usuario drop constraint gnupanel_u_d_u-- (is implicitly done)
-- alter table gnupanel_bases_de_datos drop constraint gnupanel_t_b_b_d_d-- (is implicitly done)
-- alter table gnupanel_pdns_records_nat drop constraint gnupanel_p_d_n_p_r_n-- (is implicitly done)
-- alter table gnupanel_pdns_domains_nat drop constraint gnupanel_p_d_p_d_n-- (is implicitly done)
-- alter table gnupanel_apache_dir_prot drop constraint gnupanel_a_a_d_p-- (is implicitly done)
-- alter table gnupanel_apacheconf drop constraint gnupanel_p_r_a-- (is implicitly done)
-- alter table gnupanel_mensajes_lang drop constraint gnupanel_l_m_l-- (is implicitly done)
-- alter table gnupanel_login_lang drop constraint gnupanel_l_l_l-- (is implicitly done)
-- alter table gnupanel_botones_lang drop constraint gnupanel_l_b_l-- (is implicitly done)
-- alter table gnupanel_apache_otras_conf drop constraint gnupanel_a_a_o_c-- (is implicitly done)
-- alter table gnupanel_reseller_precios_extras drop constraint gnupanel_a_r_p_e-- (is implicitly done)
-- alter table gnupanel_usuarios_precios_extras drop constraint gnupanel_r_u_p_e-- (is implicitly done)
-- alter table gnupanel_postfix_transport_listas drop constraint gnupanel_p_l_p_t_l-- (is implicitly done)
-- alter table gnupanel_postfix_listas drop constraint gnupanel_postfix_transport-- (is implicitly done)
-- alter table gnupanel_usuario_extras drop constraint gnupanel_u_p_e_u_e-- (is implicitly done)
-- alter table gnupanel_reseller_extras drop constraint gnupanel_r_p_e_r_e-- (is implicitly done)
-- alter table gnupanel_informes_admin drop constraint gnupanel_a_i_a-- (is implicitly done)
-- alter table gnupanel_informes_reseller drop constraint gnupanel_r_i_r-- (is implicitly done)
-- alter table paypal_admin drop constraint gnupanel_a_p_a_paypal-- (is implicitly done)
-- alter table paypal_reseller drop constraint gnupanel_r_p_r_paypal-- (is implicitly done)
-- alter table pagos_reseller drop constraint gnupanel_r_p_r_pagos-- (is implicitly done)
-- alter table pagos_usuario drop constraint gnupanel_u_p_u_pagos-- (is implicitly done)
-- alter table cuentadigital_admin drop constraint gnupanel_a_cuentadigital_a-- (is implicitly done)
-- alter table cuentadigital_reseller drop constraint gnupanel_r_cuentadigital_r-- (is implicitly done)
-- alter table dineromail_admin drop constraint gnupanel_a_dineromail_a-- (is implicitly done)
-- alter table dineromail_reseller drop constraint gnupanel_r_dineromail_r-- (is implicitly done)
-- alter table gnupanel_usuarios_dominios drop constraint gnupanel_u_u_d_parking-- (is implicitly done)
-- alter table gnupanel_postfix_autoreply drop constraint gnupanel_p_m_p_a-- (is implicitly done)
-- alter table gnupanel_postfix_autoreply_cola drop constraint gnupanel_p_a_p_a_c-- (is implicitly done)
-- alter table gnupanel_transferencias_historico drop constraint gnupanel_t_t_h-- (is implicitly done)
-- alter table gnupanel_espacio_historico drop constraint gnupanel_e_e_h-- (is implicitly done)


-- Generated Permissions Drops
-- --------------------------------------------------------------------
--     Target Database:   postgres
--     SQL Generator:     tedia2sql -- v1.2.12
--     Generated at:      Sun Jul 29 11:07:14 2007
--     Input Files:       Diagrama_Base_De_Datos_GNUPanel.dia




-- Generated SQL View Drop Statements
-- --------------------------------------------------------------------
--     Target Database:   postgres
--     SQL Generator:     tedia2sql -- v1.2.12
--     Generated at:      Sun Jul 29 11:07:14 2007
--     Input Files:       Diagrama_Base_De_Datos_GNUPanel.dia



-- Generated SQL Schema Drop statements
-- --------------------------------------------------------------------
--     Target Database:   postgres
--     SQL Generator:     tedia2sql -- v1.2.12
--     Generated at:      Sun Jul 29 11:07:14 2007
--     Input Files:       Diagrama_Base_De_Datos_GNUPanel.dia

drop table gnupanel_usuario cascade ;
drop table gnupanel_usuario_data cascade ;
drop table gnupanel_usuario_estado cascade ;
drop table gnupanel_usuario_plan cascade ;
drop table gnupanel_usuarios_planes cascade ;
drop table gnupanel_admin cascade ;
drop table gnupanel_ips_servidor cascade ;
drop table gnupanel_tickets_usuarios cascade ;
drop table gnupanel_reseller cascade ;
drop table gnupanel_reseller_data cascade ;
drop table gnupanel_apache_user cascade ;
drop table gnupanel_postfix_transport cascade ;
drop table gnupanel_postfix_mailuser cascade ;
drop table gnupanel_postfix_virtual cascade ;
drop table gnupanel_postfix_alias cascade ;
drop table gnupanel_pdns_domains cascade ;
drop table gnupanel_pdns_records cascade ;
drop table gnupanel_pdns_supermasters cascade ;
drop table gnupanel_proftpd_ftpuser cascade ;
drop table gnupanel_proftpd_ftpgroup cascade ;
drop table gnupanel_proftpd_ftpquotalimits cascade ;
drop table gnupanel_proftpd_ftpquotatallies cascade ;
drop table gnupanel_espacio cascade ;
drop table gnupanel_apacheconf cascade ;
drop table gnupanel_transferencias cascade ;
drop table gnupanel_reseller_estado cascade ;
drop table gnupanel_reseller_plan cascade ;
drop table gnupanel_reseller_planes cascade ;
drop table gnupanel_tickets_reseller cascade ;
drop table gnupanel_sesiones cascade ;
drop table gnupanel_bases_de_datos cascade ;
drop table gnupanel_usuarios_base cascade ;
drop table gnupanel_usuarios_facturas cascade ;
drop table gnupanel_reseller_facturas cascade ;
drop table gnupanel_lang cascade ;
drop table gnupanel_admin_lang cascade ;
drop table gnupanel_reseller_lang cascade ;
drop table gnupanel_usuario_lang cascade ;
drop table gnupanel_admin_sets cascade ;
drop table gnupanel_reseller_sets cascade ;
drop table gnupanel_usuario_sets cascade ;
drop table gnupanel_server_data cascade ;
drop table gnupanel_servidores cascade ;
drop table gnupanel_mensajes_lang cascade ;
drop table gnupanel_temas cascade ;
drop table gnupanel_reseller_extras cascade ;
drop table gnupanel_usuario_extras cascade ;
drop table gnupanel_servidores_secundarios cascade ;
drop table gnupanel_divisas_reseller cascade ;
drop table gnupanel_divisas_usuario cascade ;
drop table gnupanel_tipos_base cascade ;
drop table gnupanel_pdns_domains_nat cascade ;
drop table gnupanel_pdns_records_nat cascade ;
drop table gnupanel_pdns_supermasters_nat cascade ;
drop table apache_dominios_conf cascade ;
drop table gnupanel_apache_dir_prot cascade ;
drop table paises cascade ;
drop table gnupanel_apachedesconf cascade ;
drop table gnupanel_login_lang cascade ;
drop table gnupanel_botones_lang cascade ;
drop table gnupanel_apache_otras_conf cascade ;
drop table gnupanel_reseller_precios_extras cascade ;
drop table gnupanel_usuarios_precios_extras cascade ;
drop table gnupanel_monedas cascade ;
drop table gnupanel_postfix_listas cascade ;
drop table gnupanel_postfix_transport_listas cascade ;
drop table gnupanel_postfix_listas_remover cascade ;
drop table gnupanel_informes_admin cascade ;
drop table gnupanel_informes_reseller cascade ;
drop table paypal_admin cascade ;
drop table paypal_reseller cascade ;
drop table pagos_reseller cascade ;
drop table pagos_usuario cascade ;
drop table cuentadigital_admin cascade ;
drop table cuentadigital_reseller cascade ;
drop table dineromail_admin cascade ;
drop table dineromail_reseller cascade ;
drop table gnupanel_usuarios_dominios cascade ;
drop table gnupanel_postfix_autoreply cascade ;
drop table gnupanel_postfix_autoreply_cola cascade ;
drop table gnupanel_transferencias_historico cascade ;
drop table gnupanel_espacio_historico cascade ;


-- Generated SQL Schema
-- --------------------------------------------------------------------
--     Target Database:   postgres
--     SQL Generator:     tedia2sql -- v1.2.12
--     Generated at:      Sun Jul 29 11:07:14 2007
--     Input Files:       Diagrama_Base_De_Datos_GNUPanel.dia


-- gnupanel_usuario
create table gnupanel_usuario (
  id_usuario                serial not null,
  usuario                   varchar(255) not null,
  dominio                   varchar(255) not null,
  correo_contacto           varchar(255) not null,
  ip                        varchar(25) null,
  password                  varchar(255) not null,
  categoria                 int default 100 not null,
  cliente_de                int not null,
  active                    int default 1 not null,
  constraint pk_Gnupanel_usuario primary key (id_usuario)
) ;

-- gnupanel_usuario_data
create table gnupanel_usuario_data (
  id_usuario                int not null,
  usuario_desde             timestamp default now(),
  primer_nombre             varchar(255) null,
  segundo_nombre            varchar(255) null,
  apellido                  varchar(255) null,
  compania                  varchar(255) null,
  pais                      varchar(4) null,
  provincia                 varchar(255) null,
  ciudad                    varchar(255) null,
  calle                     varchar(255) null,
  numero                    int null,
  piso                      int null,
  departamento              varchar(255) null,
  codpostal                 varchar(255) null,
  telefono                  varchar(255) null,
  telefono_celular          varchar(255) null,
  fax                       varchar(255) null,
  constraint pk_Gnupanel_usuario_data primary key (id_usuario)
) ;

-- gnupanel_usuario_estado
create table gnupanel_usuario_estado (
  id_usuario                int not null,
  vencimiento_plan          timestamp,
  vigencia_plan             int null,
  subdominios               int default 0 not null,
  dominios_parking          int default 0 not null,
  espacio                   bigint default 0 not null,
  transferencia             bigint default 0 not null,
  bases_postgres            int default 0 not null,
  bases_mysql               int default 0 not null,
  cuentas_correo            int default 0 not null,
  listas_correo             int default 0 not null,
  cuentas_ftp               int default 0 not null,
  constraint pk_Gnupanel_usuario_estado primary key (id_usuario)
) ;

-- gnupanel_usuario_plan
create table gnupanel_usuario_plan (
  id_usuario                int not null,
  id_plan                   int not null,
  vencimiento_plan          timestamp,
  vigencia_plan             int null,
  subdominios               int default 0 not null,
  dominios_parking          int default 0 not null,
  espacio                   bigint default 0 not null,
  transferencia             bigint default 0 not null,
  bases_postgres            int default 0 not null,
  bases_mysql               int default 0 not null,
  cuentas_correo            int default 0 not null,
  listas_correo             int default 0 not null,
  cuentas_ftp               int default 0 not null,
  constraint pk_Gnupanel_usuario_plan primary key (id_usuario)
) ;

-- gnupanel_usuarios_planes
create table gnupanel_usuarios_planes (
  id_plan                   serial not null,
  plan                      varchar(255) not null,
  vigencia                  int default 0 not null,
  id_dueno                  int not null,
  subdominios               int default 0 not null,
  dominios_parking          int default 0 not null,
  espacio                   bigint default 0 not null,
  transferencia             bigint default 0 not null,
  bases_postgres            int default 0 not null,
  bases_mysql               int default 0 not null,
  cuentas_correo            int default 0 not null,
  listas_correo             int default 0 not null,
  cuentas_ftp               int default 0 not null,
  precio                    double precision default 0 not null,
  moneda                    int default 0 not null,
  es_publico                int default 0 not null,
  constraint pk_Gnupanel_usuarios_planes primary key (id_plan)
) ;

-- gnupanel_admin
create table gnupanel_admin (
  id_admin                  serial not null,
  admin                     varchar(255) not null,
  pasaporte                 varchar(255) not null,
  categoria                 int default 10 not null,
  correo                    varchar(255) not null,
  nombre                    varchar(255),
  constraint pk_Gnupanel_admin primary key (id_admin)
) ;

-- gnupanel_ips_servidor
create table gnupanel_ips_servidor (
  id_ip                     serial not null,
  ip_publica                varchar(25) default '' not null,
  usa_nat                   int,
  ip_privada                varchar(255) null,
  id_servidor               int not null,
  es_de_id_reseller         int null,
  es_ip_principal           int,
  esta_usada                int,
  es_dns                    int,
  es_ipv6                   int default 0 not null,
  constraint pk_Gnupanel_ips_servidor primary key (id_ip)
) ;

-- gnupanel_tickets_usuarios
create table gnupanel_tickets_usuarios (
  id                        serial not null,
  id_ticket                 int default 0 not null,
  id_usuario                int not null,
  id_cliente_de             int not null,
  atendido                  int default 0 not null,
  generado                  timestamp default now(),
  asunto                    varchar(255),
  texto_p                   text,
  texto_r                   text,
  conforme                  int,
  constraint pk_Gnupanel_tickets_usuarios primary key (id)
) ;

-- gnupanel_reseller
create table gnupanel_reseller (
  id_reseller               serial not null,
  reseller                  varchar(255) not null,
  dominio                   varchar(255) not null,
  correo_contacto           varchar(255) not null,
  id_ip                     int not null,
  password                  varchar(255) not null,
  categoria                 int default 50 not null,
  cliente_de                int not null,
  active                    int default 1 not null,
  constraint pk_Gnupanel_reseller primary key (id_reseller)
) ;

-- gnupanel_reseller_data
create table gnupanel_reseller_data (
  id_reseller               int not null,
  usuario_desde             timestamp default now(),
  primer_nombre             varchar(255) null,
  segundo_nombre            varchar(255) null,
  apellido                  varchar(255) null,
  compania                  varchar(255) null,
  pais                      varchar(4) null,
  provincia                 varchar(255) null,
  ciudad                    varchar(255) null,
  calle                     varchar(255) null,
  numero                    int null,
  piso                      int null,
  departamento              varchar(255) null,
  codpostal                 varchar(255) null,
  telefono                  varchar(255) null,
  telefono_celular          varchar(255) null,
  fax                       varchar(255) null,
  constraint pk_Gnupanel_reseller_data primary key (id_reseller)
) ;

-- gnupanel_apache_user
create table gnupanel_apache_user (
  id                        serial not null,
  id_subdominio             int NOT NULL,
  id_dominio                int not null,
  userid                    varchar(255) NOT NULL,
  passwd                    varchar(255) NOT NULL,
  uid                       int default 4000 not null,
  gid                       int default 4000 not null,
  estado                    int default 0 not null,
  active                    int default 1,
  constraint pk_Gnupanel_apache_user primary key (id)
) ;

-- gnupanel_postfix_transport
create table gnupanel_postfix_transport (
  id_dominio                int not null,
  dominio                   varchar(255),
  transport                 varchar(255) default 'virtual' not null,
  constraint pk_Gnupanel_postfix_transport primary key (id_dominio)
) ;

-- gnupanel_postfix_mailuser
create table gnupanel_postfix_mailuser (
  address                   varchar(255) not null,
  id_dominio                int NOT NULL,
  dominio                   varchar(255) not null,
  passwd                    varchar(255) default '' not null,
  uid                       int default 4001 not null,
  gid                       int default 4000 not null,
  name                      varchar(255) default '' not null,
  homedir                   varchar(255) default '/var/mail/correos' not null,
  maildir                   varchar(255) default '/var/mail/correos' not null,
  mailquota                 float8 default 10,
  active                    int default 1 not null,
  constraint pk_Gnupanel_postfix_mailuser primary key (address)
) ;

-- gnupanel_postfix_virtual
create table gnupanel_postfix_virtual (
  address                   varchar(255) not null,
  goto                      varchar(255) NOT NULL,
  constraint pk_Gnupanel_postfix_virtual primary key (address)
) ;

-- gnupanel_postfix_alias
create table gnupanel_postfix_alias (
  id_dominio                int not null,
  entra                     varchar(255) not null,
  sale                      varchar(255) not null,
  dominio                   varchar(255) not null
) ;

-- gnupanel_pdns_domains
create table gnupanel_pdns_domains (
  id                        int not null,
  name                      varchar(255) NOT NULL,
  master                    varchar(20) NULL,
  last_check                int NULL,
  type                      varchar(6) NOT NULL,
  notified_serial           int NULL,
  account                   varchar(40) NULL,
  constraint pk_Gnupanel_pdns_domains primary key (id)
) ;

-- gnupanel_pdns_records
create table gnupanel_pdns_records (
  id                        serial not null,
  domain_id                 int NULL,
  name                      varchar(255) NULL,
  type                      varchar(6) NULL,
  content                   varchar(255) NULL,
  ttl                       int NULL,
  prio                      int NULL,
  change_date               int NULL,
  constraint pk_Gnupanel_pdns_records primary key (id)
) ;

-- gnupanel_pdns_supermasters
create table gnupanel_pdns_supermasters (
  ip                        varchar(25) not null,
  nameserver                varchar(255) NULL,
  account                   varchar(40) NULL,
  constraint pk_Gnupanel_pdns_supermasters primary key (ip)
) ;

-- gnupanel_proftpd_ftpuser
create table gnupanel_proftpd_ftpuser (
  id                        serial unique,
  userid                    varchar(255) not null,
  passwd                    varchar(255) default '' not null,
  id_dominio                int not null,
  dominio                   varchar(255) not null,
  uid                       int default 33 not null,
  gid                       int default 33 not null,
  homedir                   varchar(255) default '/var/www/sitios' not null,
  shell                     varchar(16) default '/bin/false' not null,
  count                     int default 0 not null,
  accessed                  timestamp without time zone default now(),
  modified                  timestamp without time zone default now(),
  active                    int default 1 not null,
  constraint pk_Gnupanel_proftpd_ftpuser primary key (userid)
) ;

-- gnupanel_proftpd_ftpgroup
create table gnupanel_proftpd_ftpgroup (
  groupname                 varchar(255) default '' not null,
  gid                       int default 33 not null,
  members                   varchar(255) not null,
  constraint pk_Gnupanel_proftpd_ftpgroup primary key (members)
) ;

-- gnupanel_proftpd_ftpquotalimits
create table gnupanel_proftpd_ftpquotalimits (
  name                      varchar(255) not null,
  quota_type                varchar(8) not null check (quota_type in ('user','group','class','all')),
  per_session               boolean not null,
  limit_type                varchar(4) not null check (limit_type in ('soft','hard')),
  bytes_in_avail            float8 not null,
  bytes_out_avail           float8 not null,
  bytes_xfer_avail          float8 not null,
  files_in_avail            int8 not null,
  files_out_avail           int8 not null,
  files_xfer_avail          int8 not null,
  constraint pk_Gnupanel_proftpd_ftpquotalimits primary key (name)
) ;

-- gnupanel_proftpd_ftpquotatallies
create table gnupanel_proftpd_ftpquotatallies (
  name                      varchar(255) not null,
  quota_type                varchar(8) not null check (quota_type in ('user','group','class','all')),
  bytes_in_used             float8 not null,
  bytes_out_used            float8 not null,
  bytes_xfer_used           float8 not null,
  files_in_used             int8 not null,
  files_out_used            int8 not null,
  files_xfer_used           int8 not null,
  constraint pk_Gnupanel_proftpd_ftpquotatallies primary key (name)
) ;

-- gnupanel_espacio
create table gnupanel_espacio (
  id_dominio                int not null,
  dominio                   varchar(255) null,
  dueno                     int,
  ftpweb                    bigint default 0 not null,
  correo                    bigint default 0 not null,
  postgres                  bigint default 0 not null,
  mysql                     bigint default 0 not null,
  total                     bigint default 0 not null,
  tope                      bigint default 0 not null,
  constraint pk_Gnupanel_espacio primary key (id_dominio)
) ;

-- gnupanel_apacheconf
create table gnupanel_apacheconf (
  id_apache                 serial not null,
  id_subdominio             int not null,
  id_dominio                int not null,
  subdominio                varchar(255) default 'www' not null,
  ip                        varchar(25) default '' not null,
  puerto                    int default 80 not null,
  documentroot              varchar(255) default '/usr/share/gnupanel/gnupanel' not null,
  serveradmin               varchar(255) default '' not null,
  redirigir                 int default 0 not null,
  dominio_destino           varchar(255) null,
  es_ssl                    int default 0 not null,
  php_register_globals      int default 0 not null,
  php_safe_mode             int default 1 not null,
  indexar                   int default 0 not null,
  estado                    int default 0 not null,
  active                    int default 1 not null,
  caracteres                varchar(255) default 'ISO-8859-1',
  constraint pk_Gnupanel_apacheconf primary key (id_apache)
) ;

-- gnupanel_transferencias
create table gnupanel_transferencias (
  id_dominio                int not null,
  dominio                   varchar(255) null,
  dueno                     int,
  http                      bigint default 0 not null,
  ftp                       bigint default 0 not null,
  smtp                      bigint default 0 not null,
  pop3                      bigint default 0 not null,
  total                     bigint default 0 not null,
  tope                      bigint default 0 not null,
  constraint pk_Gnupanel_transferencias primary key (id_dominio)
) ;

-- gnupanel_reseller_estado
create table gnupanel_reseller_estado (
  id_reseller               int not null,
  vencimiento_plan          timestamp,
  vigencia_plan             int null,
  dominios                  int default 0 not null,
  subdominios               int default 0 not null,
  dominios_parking          int default 0 not null,
  espacio                   bigint default 0 not null,
  transferencia             bigint default 0 not null,
  bases_postgres            int default 0 not null,
  bases_mysql               int default 0 not null,
  cuentas_correo            int default 0 not null,
  listas_correo             int default 0 not null,
  cuentas_ftp               int default 0 not null,
  constraint pk_Gnupanel_reseller_estado primary key (id_reseller)
) ;

-- gnupanel_reseller_plan
create table gnupanel_reseller_plan (
  id_reseller               int not null,
  id_plan                   int not null,
  vencimiento_plan          timestamp,
  vigencia_plan             int null,
  dominios                  int default 0 not null,
  subdominios               int default 0 not null,
  dominios_parking          int default 0 not null,
  espacio                   bigint default 0 not null,
  transferencia             bigint default 0 not null,
  bases_postgres            int default 0 not null,
  bases_mysql               int default 0 not null,
  cuentas_correo            int default 0 not null,
  listas_correo             int default 0 not null,
  cuentas_ftp               int default 0 not null,
  constraint pk_Gnupanel_reseller_plan primary key (id_reseller)
) ;

-- gnupanel_reseller_planes
create table gnupanel_reseller_planes (
  id_plan                   serial not null,
  plan                      varchar(255) not null,
  vigencia                  int default 0 not null,
  id_dueno                  int not null,
  dominios                  int default 0 not null,
  subdominios               int default 0 not null,
  dominios_parking          int default 0 not null,
  espacio                   bigint default 0 not null,
  transferencia             bigint default 0 not null,
  bases_postgres            int default 0 not null,
  bases_mysql               int default 0 not null,
  cuentas_correo            int default 0 not null,
  listas_correo             int default 0 not null,
  cuentas_ftp               int default 0 not null,
  precio                    double precision default 0 not null,
  moneda                    int default 0 not null,
  es_publico                int default 0 not null,
  constraint pk_Gnupanel_reseller_planes primary key (id_plan)
) ;

-- gnupanel_tickets_reseller
create table gnupanel_tickets_reseller (
  id                        serial not null,
  id_ticket                 int default 0 not null,
  id_reseller               int not null,
  id_cliente_de             int not null,
  atendido                  int default 0 not null,
  generado                  timestamp default now(),
  asunto                    varchar(255),
  texto_p                   text,
  texto_r                   text,
  conforme                  int,
  constraint pk_Gnupanel_tickets_reseller primary key (id)
) ;

-- gnupanel_sesiones
create table gnupanel_sesiones (
  id_sesion                 varchar(32) not null,
  last_active               bigint,
  data                      text,
  constraint pk_Gnupanel_sesiones primary key (id_sesion)
) ;

-- gnupanel_bases_de_datos
create table gnupanel_bases_de_datos (
  id_base                   serial not null,
  id_dueno                  int not null,
  id_tipo_base              int default 1 not null,
  nombre_base               varchar(255) not null,
  estado                    int default 1,
  constraint pk_Gnupanel_bases_de_datos primary key (id_base)
) ;

-- gnupanel_usuarios_base
create table gnupanel_usuarios_base (
  base_user                 varchar(255) not null,
  id_base                   int not null
) ;

-- gnupanel_usuarios_facturas
create table gnupanel_usuarios_facturas (
  id_factura                serial not null,
  id_reseller               int not null,
  id_usuario                int not null,
  id_plan                   int not null,
  vigencia                  int default 0 not null,
  dominios                  int default 0 not null,
  subdominios               int default 0 not null,
  dominios_parking          int default 0 not null,
  espacio                   bigint default 0 not null,
  transferencia             bigint default 0 not null,
  bases_postgres            int default 0 not null,
  bases_mysql               int default 0 not null,
  cuentas_correo            int default 0 not null,
  listas_correo             int default 0 not null,
  cuentas_ftp               int default 0 not null,
  disponible_1              int null,
  disponible_2              int null,
  disponible_3              int null,
  disponible_4              int null,
  impuesto                  double precision,
  importe                   double precision default 0 not null,
  moneda                    varchar(20) default '' not null,
  esta_pago                 int,
  fecha_pago                timestamp null,
  comienzo_periodo          timestamp not null,
  fin_periodo               timestamp not null,
  constraint pk_Gnupanel_usuarios_facturas primary key (id_factura)
) ;

-- gnupanel_reseller_facturas
create table gnupanel_reseller_facturas (
  id_factura                serial not null,
  id_admin                  int not null,
  id_reseller               int not null,
  id_plan                   int not null,
  vigencia                  int default 0 not null,
  id_dueno                  int not null,
  dominios                  int default 0 not null,
  subdominios               int default 0 not null,
  dominios_parking          int default 0 not null,
  espacio                   bigint default 0 not null,
  transferencia             bigint default 0 not null,
  bases_postgres            int default 0 not null,
  bases_mysql               int default 0 not null,
  cuentas_correo            int default 0 not null,
  listas_correo             int default 0 not null,
  cuentas_ftp               int default 0 not null,
  disponible_1              int null,
  disponible_2              int null,
  disponible_3              int null,
  disponible_4              int null,
  impuesto                  double precision,
  importe                   double precision default 0 not null,
  moneda                    int default 0 not null,
  esta_pago                 int,
  fecha_pago                timestamp null,
  comienzo_periodo          timestamp not null,
  fin_periodo               timestamp not null,
  constraint pk_Gnupanel_reseller_facturas primary key (id_factura)
) ;

-- gnupanel_lang
create table gnupanel_lang (
  idioma                    varchar(4) not null,
  descripcion               varchar(255) not null,
  constraint pk_Gnupanel_lang primary key (idioma)
) ;

-- gnupanel_admin_lang
create table gnupanel_admin_lang (
  id_admin                  int not null,
  idioma                    varchar(4) not null,
  constraint pk_Gnupanel_admin_lang primary key (id_admin)
) ;

-- gnupanel_reseller_lang
create table gnupanel_reseller_lang (
  id_reseller               int not null,
  idioma                    varchar(4) not null,
  constraint pk_Gnupanel_reseller_lang primary key (id_reseller)
) ;

-- gnupanel_usuario_lang
create table gnupanel_usuario_lang (
  id_usuario                int not null,
  idioma                    varchar(4) not null,
  constraint pk_Gnupanel_usuario_lang primary key (id_usuario)
) ;

-- gnupanel_admin_sets
create table gnupanel_admin_sets (
  id_sets                   serial not null,
  id_admin                  int not null,
  tiempo_max_sesion         int default 900,
  cant_max_result           int default 10,
  politica_de_suspencion    int default 0 not null,
  id_tema                   int,
  dias_de_gracia            int default 15 not null,
  constraint pk_Gnupanel_admin_sets primary key (id_sets)
) ;

-- gnupanel_reseller_sets
create table gnupanel_reseller_sets (
  id_sets                   serial not null,
  id_reseller               int not null,
  tiempo_max_sesion         int default 900,
  cant_max_result           int default 10,
  politica_de_suspencion    int default 0 not null,
  id_tema                   int,
  dias_de_gracia            int default 15 not null,
  constraint pk_Gnupanel_reseller_sets primary key (id_sets)
) ;

-- gnupanel_usuario_sets
create table gnupanel_usuario_sets (
  id_sets                   serial not null,
  id_usuario                int not null,
  tiempo_max_sesion         int default 900,
  cant_max_result           int default 10,
  id_tema                   int,
  constraint pk_Gnupanel_usuario_sets primary key (id_sets)
) ;

-- gnupanel_server_data
create table gnupanel_server_data (
  id_data                   serial not null,
  id_servidor               int not null,
  uptime                    varchar(255),
  procesador_data           varchar(255),
  procesador_uso            int,
  memoria_total             int,
  memoria_usada             int,
  swap_total                int,
  swap_usada                int,
  disco_total               int,
  disco_usado               int,
  constraint pk_Gnupanel_server_data primary key (id_data)
) ;

-- gnupanel_servidores
create table gnupanel_servidores (
  id_servidor               serial not null,
  servidor                  varchar(255) not null,
  constraint pk_Gnupanel_servidores primary key (id_servidor)
) ;

-- gnupanel_mensajes_lang
create table gnupanel_mensajes_lang (
  id                        serial not null,
  idioma                    varchar(4) not null,
  interfaz                  varchar(255) not null,
  seccion                   varchar(255) not null,
  plugin                    varchar(255) not null,
  llave                     varchar(40) not null,
  mensaje                   text not null,
  constraint pk_Gnupanel_mensajes_lang primary key (id)
) ;

-- gnupanel_temas
create table gnupanel_temas (
  id_tema                   serial not null,
  tema                      varchar(255),
  constraint pk_Gnupanel_temas primary key (id_tema)
) ;

-- gnupanel_reseller_extras
create table gnupanel_reseller_extras (
  id_reseller               int not null,
  vencimiento_extra         timestamp,
  id_extra                  int not null
) ;

-- gnupanel_usuario_extras
create table gnupanel_usuario_extras (
  id_usuario                int not null,
  vencimiento_extra         timestamp,
  id_extra                  int not null
) ;

-- gnupanel_servidores_secundarios
create table gnupanel_servidores_secundarios (
  id_secundario             serial not null,
  secundario                varchar(255) not null,
  id_servidor               int not null,
  ip                        varchar(25) default '' not null,
  es_dns                    int,
  es_mx                     int,
  subdominio_ns             varchar(9) default '' not null,
  subdominio_mx             varchar(9) default '' not null,
  constraint pk_Gnupanel_servidores_secundarios primary key (id_secundario)
) ;

-- gnupanel_divisas_reseller
create table gnupanel_divisas_reseller (
  id_reseller               int not null,
  credito                   double precision default 0 not null,
  vencimiento               timestamp null,
  constraint pk_Gnupanel_divisas_reseller primary key (id_reseller)
) ;

-- gnupanel_divisas_usuario
create table gnupanel_divisas_usuario (
  id_usuario                int not null,
  credito                   double precision default 0 not null,
  vencimiento               timestamp null,
  constraint pk_Gnupanel_divisas_usuario primary key (id_usuario)
) ;

-- gnupanel_tipos_base
create table gnupanel_tipos_base (
  id_tipo_base              int not null,
  tipo_base                 varchar(255) not null,
  constraint pk_Gnupanel_tipos_base primary key (id_tipo_base)
) ;

-- gnupanel_pdns_domains_nat
create table gnupanel_pdns_domains_nat (
  id                        int not null,
  name                      varchar(255) NOT NULL,
  master                    varchar(20) NULL,
  last_check                int NULL,
  type                      varchar(6) NOT NULL,
  notified_serial           int NULL,
  account                   varchar(40) NULL,
  constraint pk_Gnupanel_pdns_domains_nat primary key (id)
) ;

-- gnupanel_pdns_records_nat
create table gnupanel_pdns_records_nat (
  id                        serial not null,
  domain_id                 int NULL,
  name                      varchar(255) NULL,
  type                      varchar(6) NULL,
  content                   varchar(255) NULL,
  ttl                       int NULL,
  prio                      int NULL,
  change_date               int NULL,
  constraint pk_Gnupanel_pdns_records_nat primary key (id)
) ;

-- gnupanel_pdns_supermasters_nat
create table gnupanel_pdns_supermasters_nat (
  ip                        varchar(25) not null,
  nameserver                varchar(255) NULL,
  account                   varchar(40) NULL,
  constraint pk_Gnupanel_pdns_supermasters_nat primary key (ip)
) ;

-- apache_dominios_conf
create table apache_dominios_conf (
  id                        int default 0 not null not null,
  configurar                int default 0 not null,
  constraint pk_Apache_dominios_conf primary key (id)
) ;

-- gnupanel_apache_dir_prot
create table gnupanel_apache_dir_prot (
  id_directorio             serial not null,
  id_subdominio             int not null,
  directorio                varchar(1024) default '' not null,
  descripcion               varchar(255) default '' not null,
  constraint pk_Gnupanel_apache_dir_prot primary key (id_directorio)
) ;

-- paises
create table paises (
  iso                       varchar(2) not null,
  nombre                    varchar(80) not null,
  descripcion               varchar(80) not null,
  iso3                      varchar(3) null,
  numcode                   varchar(4) null,
  constraint pk_Paises primary key (iso)
) ;

-- gnupanel_apachedesconf
create table gnupanel_apachedesconf (
  id_subdominio             int not null,
  id_dominio                int not null,
  subdominio                varchar(255) default 'www' not null,
  ip                        varchar(25) default '' not null,
  puerto                    int default 80 not null,
  documentroot              varchar(255) default '/var/www/sitios/default' not null,
  serveradmin               varchar(255) default '' not null,
  redirigir                 int default 0 not null,
  dominio_destino           varchar(255) null,
  es_ssl                    int default 0 not null,
  php_register_globals      int default 0 not null,
  php_safe_mode             int default 1 not null,
  estado                    int default 0 not null,
  active                    int default 0 not null
) ;

-- gnupanel_login_lang
create table gnupanel_login_lang (
  id                        serial not null,
  idioma                    varchar(4) not null,
  interfaz                  varchar(255) not null,
  llave                     varchar(40) not null,
  mensaje                   text not null,
  constraint pk_Gnupanel_login_lang primary key (id)
) ;

-- gnupanel_botones_lang
create table gnupanel_botones_lang (
  id                        serial not null,
  idioma                    varchar(4) not null,
  interfaz                  varchar(255) not null,
  seccion                   varchar(255) not null,
  plugin                    varchar(255) not null,
  mensaje                   text not null,
  constraint pk_Gnupanel_botones_lang primary key (id)
) ;

-- gnupanel_apache_otras_conf
create table gnupanel_apache_otras_conf (
  id                        serial not null,
  id_subdominio             int not null,
  dir_indexes               varchar(255) not null,
  disponible_0              varchar(255) null,
  disponible_1              varchar(255) null,
  disponible_2              varchar(255) null,
  disponible_3              varchar(255) null,
  disponible_4              varchar(255) null,
  constraint pk_Gnupanel_apache_otras_conf primary key (id)
) ;

-- gnupanel_reseller_precios_extras
create table gnupanel_reseller_precios_extras (
  id_extra                  serial not null,
  periodo                   int default 1 not null,
  id_dueno                  int not null,
  cantidad                  int default 0 not null,
  servicio                  varchar(255) default '' not null,
  precio                    double precision default 0 not null,
  id_moneda                 bigint default 0 not null,
  constraint pk_Gnupanel_reseller_precios_extras primary key (id_extra)
) ;

-- gnupanel_usuarios_precios_extras
create table gnupanel_usuarios_precios_extras (
  id_extra                  serial not null,
  periodo                   int default 1 not null,
  id_dueno                  int not null,
  cantidad                  int default 0 not null,
  servicio                  varchar(255) default '' not null,
  precio                    double precision default 0 not null,
  id_moneda                 int default 0 not null,
  constraint pk_Gnupanel_usuarios_precios_extras primary key (id_extra)
) ;

-- gnupanel_monedas
create table gnupanel_monedas (
  id_moneda                 int default 0 not null not null,
  moneda                    varchar(21) default 'DOLAR',
  constraint pk_Gnupanel_monedas primary key (id_moneda)
) ;

-- gnupanel_postfix_listas
create table gnupanel_postfix_listas (
  id_lista                  serial not null,
  nombre_lista              varchar(255) default '' not null,
  correo_admin_lista        varchar(255) default '' not null,
  password                  varchar(255) default '*' not null,
  id_dominio                int NOT NULL,
  dominio                   varchar(255),
  estado                    int default 0 not null,
  active                    int default 1 not null,
  constraint pk_Gnupanel_postfix_listas primary key (id_lista)
) ;

-- gnupanel_postfix_transport_listas
create table gnupanel_postfix_transport_listas (
  id                        serial not null,
  id_lista                  int not null,
  direccion                 varchar(255),
  transport                 varchar(255) default 'local' not null,
  constraint pk_Gnupanel_postfix_transport_listas primary key (id)
) ;

-- gnupanel_postfix_listas_remover
create table gnupanel_postfix_listas_remover (
  id_lista                  serial not null,
  nombre_lista              varchar(255) default '' not null,
  constraint pk_Gnupanel_postfix_listas_remover primary key (id_lista)
) ;

-- gnupanel_informes_admin
create table gnupanel_informes_admin (
  id                        serial not null,
  id_admin                  int not null,
  generado                  timestamp default now(),
  asunto                    varchar(255),
  informe                   text,
  enviado                   int default 0 not null,
  constraint pk_Gnupanel_informes_admin primary key (id)
) ;

-- gnupanel_informes_reseller
create table gnupanel_informes_reseller (
  id                        serial not null,
  id_reseller               int not null,
  generado                  timestamp default now(),
  asunto                    varchar(255),
  informe                   text,
  enviado                   int default 0 not null,
  constraint pk_Gnupanel_informes_reseller primary key (id)
) ;

-- paypal_admin
create table paypal_admin (
  id                        serial not null,
  id_admin                  int not null,
  correo_paypal             varchar(255) default '' not null,
  test                      int default 1 not null,
  active                    int default 0 not null,
  constraint pk_Paypal_admin primary key (id)
) ;

-- paypal_reseller
create table paypal_reseller (
  id                        serial not null,
  id_reseller               int not null,
  correo_paypal             varchar(255) default '' not null,
  test                      int default 1 not null,
  active                    int default 0 not null,
  constraint pk_Paypal_reseller primary key (id)
) ;

-- pagos_reseller
create table pagos_reseller (
  id                        serial not null,
  id_reseller               int not null,
  importe                   double precision default 0 not null,
  inicio_pago               timestamp default now(),
  acreditacion_pago         timestamp,
  empresa_cobranza          varchar(255) default '' not null,
  codigo_seguimiento        varchar(255) default '' not null,
  confirmado                int default 0 not null,
  acreditado                int default 0 not null,
  constraint pk_Pagos_reseller primary key (id)
) ;

-- pagos_usuario
create table pagos_usuario (
  id                        serial not null,
  id_usuario                int not null,
  importe                   double precision default 0 not null,
  inicio_pago               timestamp default now(),
  acreditacion_pago         timestamp,
  empresa_cobranza          varchar(255) default '' not null,
  codigo_seguimiento        varchar(255) default '' not null,
  confirmado                int default 0 not null,
  acreditado                int default 0 not null,
  constraint pk_Pagos_usuario primary key (id)
) ;

-- cuentadigital_admin
create table cuentadigital_admin (
  id                        serial not null,
  id_admin                  int not null,
  id_cuentadigital          varchar(255) default '' not null,
  active                    int default 0 not null,
  constraint pk_Cuentadigital_admin primary key (id)
) ;

-- cuentadigital_reseller
create table cuentadigital_reseller (
  id                        serial not null,
  id_reseller               int not null,
  id_cuentadigital          varchar(255) default '' not null,
  active                    int default 0 not null,
  constraint pk_Cuentadigital_reseller primary key (id)
) ;

-- dineromail_admin
create table dineromail_admin (
  id                        serial not null,
  id_admin                  int not null,
  id_dineromail             varchar(255) default '' not null,
  active                    int default 0 not null,
  constraint pk_Dineromail_admin primary key (id)
) ;

-- dineromail_reseller
create table dineromail_reseller (
  id                        serial not null,
  id_reseller               int not null,
  id_dineromail             varchar(255) default '' not null,
  active                    int default 0 not null,
  constraint pk_Dineromail_reseller primary key (id)
) ;

-- gnupanel_usuarios_dominios
create table gnupanel_usuarios_dominios (
  secuencia                 serial,
  id                        int not null,
  id_usuario                int not null,
  constraint pk_Gnupanel_usuarios_dominios primary key (id)
) ;

-- gnupanel_postfix_autoreply
create table gnupanel_postfix_autoreply (
  address                   varchar(255) not null,
  transport                 varchar(255) default 'autoreply' NOT NULL,
  subject                   varchar(255) NOT NULL,
  mensaje                   text NULL,
  mapa_caracteres           varchar(255) NULL,
  active                    int default 1 not null,
  constraint pk_Gnupanel_postfix_autoreply primary key (address)
) ;

-- gnupanel_postfix_autoreply_cola
create table gnupanel_postfix_autoreply_cola (
  id                        serial not null,
  address                   varchar(255),
  destino                   varchar(255) default '' NOT NULL,
  constraint pk_Gnupanel_postfix_autoreply_cola primary key (id)
) ;

-- gnupanel_transferencias_historico
create table gnupanel_transferencias_historico (
  id                        serial not null,
  ano                       int not null,
  mes                       int not null,
  fecha                     timestamp default now(),
  id_dominio                int not null,
  dominio                   varchar(255) null,
  dueno                     int,
  http                      bigint default 0 not null,
  ftp                       bigint default 0 not null,
  smtp                      bigint default 0 not null,
  pop3                      bigint default 0 not null,
  total                     bigint default 0 not null,
  tope                      bigint default 0 not null,
  constraint pk_Gnupanel_transferencias_historico primary key (id)
) ;

-- gnupanel_espacio_historico
create table gnupanel_espacio_historico (
  id                        serial not null,
  ano                       int not null,
  mes                       int not null,
  fecha                     timestamp default now(),
  id_dominio                int NOT NULL,
  dominio                   varchar(255) null,
  dueno                     int,
  ftpweb                    bigint default 0 not null,
  correo                    bigint default 0 not null,
  postgres                  bigint default 0 not null,
  mysql                     bigint default 0 not null,
  total                     bigint default 0 not null,
  tope                      bigint default 0 not null,
  constraint pk_Gnupanel_espacio_historico primary key (id)
) ;




















































































-- Generated SQL Views
-- --------------------------------------------------------------------
--     Target Database:   postgres
--     SQL Generator:     tedia2sql -- v1.2.12
--     Generated at:      Sun Jul 29 11:07:14 2007
--     Input Files:       Diagrama_Base_De_Datos_GNUPanel.dia




-- Generated Permissions
-- --------------------------------------------------------------------
--     Target Database:   postgres
--     SQL Generator:     tedia2sql -- v1.2.12
--     Generated at:      Sun Jul 29 11:07:14 2007
--     Input Files:       Diagrama_Base_De_Datos_GNUPanel.dia



-- Generated SQL Insert statements
-- --------------------------------------------------------------------
--     Target Database:   postgres
--     SQL Generator:     tedia2sql -- v1.2.12
--     Generated at:      Sun Jul 29 11:07:14 2007
--     Input Files:       Diagrama_Base_De_Datos_GNUPanel.dia



-- Generated SQL Constraints
-- --------------------------------------------------------------------
--     Target Database:   postgres
--     SQL Generator:     tedia2sql -- v1.2.12
--     Generated at:      Sun Jul 29 11:07:14 2007
--     Input Files:       Diagrama_Base_De_Datos_GNUPanel.dia

alter table gnupanel_usuario_data add constraint gnupanel_u_d
  foreign key (id_usuario)
  references gnupanel_usuario (id_usuario) on update cascade on delete cascade ;
alter table gnupanel_usuario add constraint gnupanel_r_u
  foreign key (cliente_de)
  references gnupanel_reseller (id_reseller) on update cascade on delete cascade ;
alter table gnupanel_reseller add constraint gnupanel_a_r
  foreign key (cliente_de)
  references gnupanel_admin (id_admin) on update cascade on delete cascade ;
alter table gnupanel_reseller_data add constraint gnupanel_r_r_d
  foreign key (id_reseller)
  references gnupanel_reseller (id_reseller) on update cascade on delete cascade ;
alter table gnupanel_usuarios_planes add constraint gnupanel_r_u_p
  foreign key (id_dueno)
  references gnupanel_reseller (id_reseller) on update cascade on delete cascade ;
alter table gnupanel_usuario_plan add constraint gnupanel_u_u_p
  foreign key (id_usuario)
  references gnupanel_usuario (id_usuario) on update cascade on delete cascade ;
alter table gnupanel_usuario_estado add constraint gnupanel_u_u_e
  foreign key (id_usuario)
  references gnupanel_usuario (id_usuario) on update cascade on delete cascade ;
alter table gnupanel_tickets_usuarios add constraint gnupanel_u_t_p
  foreign key (id_usuario)
  references gnupanel_usuario (id_usuario) on update cascade on delete cascade ;
alter table gnupanel_pdns_domains add constraint gnupanel_u_p_d
  foreign key (id)
  references gnupanel_usuarios_dominios (id) on update cascade on delete cascade ;
alter table gnupanel_postfix_mailuser add constraint gnupanel_p_t_p_m
  foreign key (id_dominio)
  references gnupanel_postfix_transport (id_dominio) ON DELETE CASCADE ;
alter table gnupanel_postfix_virtual add constraint gnupanel_p_m_p_v
  foreign key (address)
  references gnupanel_postfix_mailuser (address) ON DELETE CASCADE ;
alter table gnupanel_pdns_records add constraint gnupanel_p_d_r
  foreign key (domain_id)
  references gnupanel_pdns_domains (id) ON DELETE CASCADE ;
alter table gnupanel_proftpd_ftpgroup add constraint gnupanel_p_f_p_f
  foreign key (members)
  references gnupanel_proftpd_ftpuser (userid) ON DELETE CASCADE ;
alter table gnupanel_proftpd_ftpquotalimits add constraint gnupanel_p_f_p_fquli
  foreign key (name)
  references gnupanel_proftpd_ftpgroup (members) ON DELETE CASCADE ;
alter table gnupanel_proftpd_ftpquotatallies add constraint gnupanel_p_fquli_p_fquta
  foreign key (name)
  references gnupanel_proftpd_ftpquotalimits (name) ON DELETE CASCADE ;
alter table gnupanel_postfix_alias add constraint gnupanel_p_t_p_a
  foreign key (id_dominio)
  references gnupanel_postfix_transport (id_dominio) on delete cascade ;
alter table gnupanel_apacheconf add constraint pdns_p_d_a
  foreign key (id_dominio)
  references gnupanel_pdns_domains (id) on update cascade on delete cascade ;
alter table gnupanel_apache_user add constraint gnupanel_a_a_u
  foreign key (id_subdominio)
  references gnupanel_apacheconf (id_apache) on update cascade on delete cascade ;
alter table gnupanel_postfix_transport add constraint gnupanel_p_d_p_t
  foreign key (id_dominio)
  references gnupanel_pdns_domains (id) on delete cascade ;
alter table gnupanel_proftpd_ftpuser add constraint gnupanel_p_d_p_u
  foreign key (id_dominio)
  references gnupanel_pdns_domains (id) on delete cascade ;
alter table gnupanel_transferencias add constraint gnupanel_p_d_t
  foreign key (id_dominio)
  references gnupanel_pdns_domains (id) on update cascade on delete cascade ;
alter table gnupanel_espacio add constraint gnupanel_t_e
  foreign key (id_dominio)
  references gnupanel_transferencias (id_dominio) on update cascade on delete cascade ;
alter table gnupanel_reseller_plan add constraint gnupanel_r_r_p
  foreign key (id_reseller)
  references gnupanel_reseller (id_reseller) on update cascade on delete cascade ;
alter table gnupanel_reseller_estado add constraint gnupanel_r_r_e
  foreign key (id_reseller)
  references gnupanel_reseller (id_reseller) on update cascade on delete cascade ;
alter table gnupanel_reseller_planes add constraint gnupanel_a_r_p
  foreign key (id_dueno)
  references gnupanel_admin (id_admin) on update cascade on delete cascade ;
alter table gnupanel_tickets_reseller add constraint gnupanel_r_t_r
  foreign key (id_reseller)
  references gnupanel_reseller (id_reseller) on update cascade on delete cascade ;
alter table gnupanel_reseller add constraint gnupanel_i_s_u
  foreign key (id_ip)
  references gnupanel_ips_servidor (id_ip) on update cascade on delete cascade ;
alter table gnupanel_bases_de_datos add constraint gnupanel_u_b_p
  foreign key (id_dueno)
  references gnupanel_usuario (id_usuario) on update cascade on delete cascade ;
alter table gnupanel_usuarios_base add constraint gnupanel_b_p_u_p
  foreign key (id_base)
  references gnupanel_bases_de_datos (id_base) on update cascade on delete cascade ;
alter table gnupanel_usuarios_facturas add constraint gnupanel_r_u_f
  foreign key (id_reseller)
  references gnupanel_reseller (id_reseller) on update cascade on delete cascade ;
alter table gnupanel_reseller_facturas add constraint gnupanel_a_r_f
  foreign key (id_admin)
  references gnupanel_admin (id_admin) on update cascade on delete cascade ;
alter table gnupanel_admin_lang add constraint gnupanel_a_a_l
  foreign key (id_admin)
  references gnupanel_admin (id_admin) on update cascade on delete cascade ;
alter table gnupanel_reseller_lang add constraint gnupanel_r_r_l
  foreign key (id_reseller)
  references gnupanel_reseller (id_reseller) on update cascade on delete cascade ;
alter table gnupanel_usuario_lang add constraint gnupanel_u_u_l
  foreign key (id_usuario)
  references gnupanel_usuario (id_usuario) on update cascade on delete cascade ;
alter table gnupanel_admin_sets add constraint gnupanel_a_a_s
  foreign key (id_admin)
  references gnupanel_admin (id_admin) on update cascade on delete cascade ;
alter table gnupanel_reseller_sets add constraint gnupanel_r_r_s
  foreign key (id_reseller)
  references gnupanel_reseller (id_reseller) on update cascade on delete cascade ;
alter table gnupanel_usuario_sets add constraint gnupanel_u_u_s
  foreign key (id_usuario)
  references gnupanel_usuario (id_usuario) on update cascade on delete cascade ;
alter table gnupanel_server_data add constraint gnupanel_s_s_d
  foreign key (id_servidor)
  references gnupanel_servidores (id_servidor) on update cascade on delete cascade ;
alter table gnupanel_ips_servidor add constraint gnupanel_s_i_s
  foreign key (id_servidor)
  references gnupanel_servidores (id_servidor) on update cascade on delete cascade ;
alter table gnupanel_reseller_extras add constraint gnupanel_r_r_e
  foreign key (id_reseller)
  references gnupanel_reseller (id_reseller) on update cascade on delete cascade ;
alter table gnupanel_usuario_extras add constraint gnupanel_u_u_e
  foreign key (id_usuario)
  references gnupanel_usuario (id_usuario) on update cascade on delete cascade ;
alter table gnupanel_servidores_secundarios add constraint gnupanel_s_s_s
  foreign key (id_servidor)
  references gnupanel_servidores (id_servidor) on update cascade on delete cascade ;
alter table gnupanel_divisas_reseller add constraint gnupanel_r_d_r
  foreign key (id_reseller)
  references gnupanel_reseller (id_reseller) on update cascade on delete cascade ;
alter table gnupanel_divisas_usuario add constraint gnupanel_u_d_u
  foreign key (id_usuario)
  references gnupanel_usuario (id_usuario) on update cascade on delete cascade ;
alter table gnupanel_bases_de_datos add constraint gnupanel_t_b_b_d_d
  foreign key (id_tipo_base)
  references gnupanel_tipos_base (id_tipo_base) on update cascade on delete cascade ;
alter table gnupanel_pdns_records_nat add constraint gnupanel_p_d_n_p_r_n
  foreign key (domain_id)
  references gnupanel_pdns_domains_nat (id) on update cascade on delete cascade ;
alter table gnupanel_pdns_domains_nat add constraint gnupanel_p_d_p_d_n
  foreign key (id)
  references gnupanel_pdns_domains (id) on update cascade on delete cascade ;
alter table gnupanel_apache_dir_prot add constraint gnupanel_a_a_d_p
  foreign key (id_subdominio)
  references gnupanel_apacheconf (id_apache) on update cascade on delete cascade ;
alter table gnupanel_apacheconf add constraint gnupanel_p_r_a
  foreign key (id_subdominio)
  references gnupanel_pdns_records (id) on update cascade on delete cascade ;
alter table gnupanel_mensajes_lang add constraint gnupanel_l_m_l
  foreign key (idioma)
  references gnupanel_lang (idioma) on update cascade on delete cascade ;
alter table gnupanel_login_lang add constraint gnupanel_l_l_l
  foreign key (idioma)
  references gnupanel_lang (idioma) on update cascade on delete cascade ;
alter table gnupanel_botones_lang add constraint gnupanel_l_b_l
  foreign key (idioma)
  references gnupanel_lang (idioma) on update cascade on delete cascade ;
alter table gnupanel_apache_otras_conf add constraint gnupanel_a_a_o_c
  foreign key (id_subdominio)
  references gnupanel_apacheconf (id_apache) on update cascade on delete cascade ;
alter table gnupanel_reseller_precios_extras add constraint gnupanel_a_r_p_e
  foreign key (id_dueno)
  references gnupanel_admin (id_admin) on update cascade on delete cascade ;
alter table gnupanel_usuarios_precios_extras add constraint gnupanel_r_u_p_e
  foreign key (id_dueno)
  references gnupanel_reseller (id_reseller) on update cascade on delete cascade ;
alter table gnupanel_postfix_transport_listas add constraint gnupanel_p_l_p_t_l
  foreign key (id_lista)
  references gnupanel_postfix_listas (id_lista) on update cascade on delete cascade ;
alter table gnupanel_postfix_listas add constraint gnupanel_postfix_transport
  foreign key (id_dominio)
  references gnupanel_postfix_transport (id_dominio) on update cascade on delete cascade ;
alter table gnupanel_usuario_extras add constraint gnupanel_u_p_e_u_e
  foreign key (id_extra)
  references gnupanel_usuarios_precios_extras (id_extra) on update cascade on delete cascade ;
alter table gnupanel_reseller_extras add constraint gnupanel_r_p_e_r_e
  foreign key (id_extra)
  references gnupanel_reseller_precios_extras (id_extra) on update cascade on delete cascade ;
alter table gnupanel_informes_admin add constraint gnupanel_a_i_a
  foreign key (id_admin)
  references gnupanel_admin (id_admin) on update cascade on delete cascade ;
alter table gnupanel_informes_reseller add constraint gnupanel_r_i_r
  foreign key (id_reseller)
  references gnupanel_reseller (id_reseller) on update cascade on delete cascade ;
alter table paypal_admin add constraint gnupanel_a_p_a_paypal
  foreign key (id_admin)
  references gnupanel_admin (id_admin) on update cascade on delete cascade ;
alter table paypal_reseller add constraint gnupanel_r_p_r_paypal
  foreign key (id_reseller)
  references gnupanel_reseller (id_reseller) on update cascade on delete cascade ;
alter table pagos_reseller add constraint gnupanel_r_p_r_pagos
  foreign key (id_reseller)
  references gnupanel_reseller (id_reseller) on update cascade on delete cascade ;
alter table pagos_usuario add constraint gnupanel_u_p_u_pagos
  foreign key (id_usuario)
  references gnupanel_usuario (id_usuario) on update cascade on delete cascade ;
alter table cuentadigital_admin add constraint gnupanel_a_cuentadigital_a
  foreign key (id_admin)
  references gnupanel_admin (id_admin) on update cascade on delete cascade ;
alter table cuentadigital_reseller add constraint gnupanel_r_cuentadigital_r
  foreign key (id_reseller)
  references gnupanel_reseller (id_reseller) on update cascade on delete cascade ;
alter table dineromail_admin add constraint gnupanel_a_dineromail_a
  foreign key (id_admin)
  references gnupanel_admin (id_admin) on update cascade on delete cascade ;
alter table dineromail_reseller add constraint gnupanel_r_dineromail_r
  foreign key (id_reseller)
  references gnupanel_reseller (id_reseller) on update cascade on delete cascade ;
alter table gnupanel_usuarios_dominios add constraint gnupanel_u_u_d_parking
  foreign key (id_usuario)
  references gnupanel_usuario (id_usuario) on update cascade on delete cascade ;
alter table gnupanel_postfix_autoreply add constraint gnupanel_p_m_p_a
  foreign key (address)
  references gnupanel_postfix_mailuser (address) ON UPDATE CASCADE ON DELETE CASCADE ;
alter table gnupanel_postfix_autoreply_cola add constraint gnupanel_p_a_p_a_c
  foreign key (address)
  references gnupanel_postfix_autoreply (address) ON UPDATE CASCADE ON DELETE CASCADE ;
alter table gnupanel_transferencias_historico add constraint gnupanel_t_t_h
  foreign key (id_dominio)
  references gnupanel_transferencias (id_dominio) ON UPDATE CASCADE ON DELETE CASCADE ;
alter table gnupanel_espacio_historico add constraint gnupanel_e_e_h
  foreign key (id_dominio)
  references gnupanel_espacio (id_dominio) ON UPDATE CASCADE ON DELETE CASCADE ;

