#! /bin/sh
### BEGIN INIT INFO
# Provides:          clamav-daemon
# Required-Start:    $remote_fs $syslog postgresql
# Should-Start:      
# Required-Stop:     $remote_fs $syslog postgresql
# Should-Stop:       
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: ClamAV daemon
# Description:       Clam AntiVirus userspace daemon
### END INIT INFO
