#! /bin/sh -e
### BEGIN INIT INFO
# Short-Description: Courier POP3-SSL server
# Provides:          courier-pop-ssl
# Required-Start:    $remote_fs $syslog postgresql
# Required-Stop:     $remote_fs $syslog postgresql
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
### END INIT INFO
