#!/bin/sh
### BEGIN INIT INFO
# Provides:          pdns-nat
# Required-Start:    $network $remote_fs $syslog postgresql
# Required-Stop:     $network $remote_fs $syslog postgresql
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Should-Start:      slapd
# Should-Stop:       slapd
# Short-Description: PDNS is a versatile high performance authoritative nameserver.
### END INIT INFO
